-- @better-auth/stripe schema. Generated by `npx better-auth generate` against
-- server/utils/auth.cli.ts with the stripe plugin enabled, then manually
-- trimmed to a forward diff (the CLI emits the whole schema).

ALTER TABLE "user" ADD COLUMN "stripeCustomerId" text;

CREATE TABLE "subscription" (
  "id" text NOT NULL PRIMARY KEY,
  "plan" text NOT NULL,
  "referenceId" text NOT NULL,
  "stripeCustomerId" text,
  "stripeSubscriptionId" text,
  "status" text NOT NULL,
  "periodStart" date,
  "periodEnd" date,
  "trialStart" date,
  "trialEnd" date,
  "cancelAtPeriodEnd" integer,
  "cancelAt" date,
  "canceledAt" date,
  "endedAt" date,
  "seats" integer,
  "billingInterval" text,
  "stripeScheduleId" text
);

CREATE INDEX "subscription_referenceId_idx" ON "subscription" ("referenceId");
CREATE INDEX "subscription_stripeSubscriptionId_idx" ON "subscription" ("stripeSubscriptionId");
